function toCursorRules(prompt) {
  return `# .cursorrules\n# Generated by Meta-Prompt Architect\n\n${prompt}`;
}

function toClinerules(prompt) {
  return `# .clinerules\n# Generated by Meta-Prompt Architect\n\n${prompt}`;
}

function toAgentsMd(prompt) {
  return `# AGENTS.md\n# Project instructions for AI agents (Claude Code, OpenCode, etc.)\n# Generated by Meta-Prompt Architect\n\n${prompt}`;
}

function toWindsurfrules(prompt) {
  return `# .windsurfrules\n# Generated by Meta-Prompt Architect\n\n${prompt}`;
}

function toCustomGpt(prompt) {
  const config = {
    name: 'Architect-Generated Assistant',
    description: 'Custom GPT instructions generated by Meta-Prompt Architect',
    instructions: prompt,
    welcome: 'Hello! I am your architect-generated assistant. How can I help you today?',
    capabilities: {
      code_interpreter: true,
      browsing: true,
      image_input: false
    }
  };
  return JSON.stringify(config, null, 2);
}

function toOpenCode(prompt) {
  const config = {
    _note: 'Prompt block generated by Meta-Prompt Architect. Paste into your opencode.json agent config under "prompt".',
    systemPrompt: prompt,
    name: 'Prompt Architect Worker',
    description: 'Generated by Meta-Prompt Architect'
  };
  return JSON.stringify(config, null, 2);
}

function toOpenCodeJsonc(prompt) {
  return `// Generated by Meta-Prompt Architect\n${toOpenCode(prompt)}`;
}

function toVSCodeSnippet(prompt, name) {
  const config = {
    [name || 'Generated Prompt']: {
      prefix: ['prompt', 'architect'],
      body: prompt.split('\n'),
      description: 'Generated by Meta-Prompt Architect'
    }
  };
  return JSON.stringify(config, null, 2);
}

function toAntigravity(prompt) {
  return `# Antigravity Instructions\n# Generated by Meta-Prompt Architect\n\n${prompt}`;
}

function toMarkdown(prompt) {
  return prompt;
}

function exportPrompt(prompt, format, name = 'generated-prompt') {
  switch (format) {
    case 'cursorrules':
      return { ext: '.cursorrules', content: toCursorRules(prompt) };
    case 'clinerules':
      return { ext: '.clinerules', content: toClinerules(prompt) };
    case 'agents-md':
      return { ext: '.md', content: toAgentsMd(prompt) };
    case 'windsurfrules':
      return { ext: '.windsurfrules', content: toWindsurfrules(prompt) };
    case 'custom-gpt':
      return { ext: '.json', content: toCustomGpt(prompt) };
    case 'opencode':
      return { ext: '.json', content: toOpenCode(prompt) };
    case 'opencode-jsonc':
      return { ext: '.jsonc', content: toOpenCodeJsonc(prompt) };
    case 'vscode':
      return { ext: '.code-snippets', content: toVSCodeSnippet(prompt, name) };
    case 'antigravity':
      return { ext: '.ag.md', content: toAntigravity(prompt) };
    case 'markdown':
    default:
      return { ext: '.md', content: toMarkdown(prompt) };
  }
}

module.exports = { exportPrompt, toCursorRules, toClinerules, toAgentsMd, toWindsurfrules, toCustomGpt, toOpenCode, toVSCodeSnippet, toAntigravity };
