function toCursorRules(prompt) {
  return `# .cursorrules\n# Generated by Meta-Prompt Architect\n\n${prompt}`;
}

function toOpenCode(prompt) {
  const config = {
    systemPrompt: prompt,
    name: 'Prompt Architect Worker',
    description: 'Generated by Meta-Prompt Architect'
  };
  return JSON.stringify(config, null, 2);
}

function toOpenCodeJsonc(prompt) {
  return `// Generated by Meta-Prompt Architect\n${toOpenCode(prompt)}`;
}

function toVSCodeSnippet(prompt, name) {
  const config = {
    [name || 'Generated Prompt']: {
      prefix: ['prompt', 'architect'],
      body: prompt.split('\n'),
      description: 'Generated by Meta-Prompt Architect'
    }
  };
  return JSON.stringify(config, null, 2);
}

function toAntigravity(prompt) {
  return `# Antigravity Instructions\n# Generated by Meta-Prompt Architect\n\n${prompt}`;
}

function toMarkdown(prompt) {
  return prompt;
}

function exportPrompt(prompt, format, name = 'generated-prompt') {
  switch (format) {
    case 'cursorrules':
      return { ext: '.cursorrules', content: toCursorRules(prompt) };
    case 'opencode':
      return { ext: '.json', content: toOpenCode(prompt) };
    case 'opencode-jsonc':
      return { ext: '.jsonc', content: toOpenCodeJsonc(prompt) };
    case 'vscode':
      return { ext: '.code-snippets', content: toVSCodeSnippet(prompt, name) };
    case 'antigravity':
      return { ext: '.ag.md', content: toAntigravity(prompt) };
    case 'markdown':
    default:
      return { ext: '.md', content: toMarkdown(prompt) };
  }
}

module.exports = { exportPrompt, toCursorRules, toOpenCode, toVSCodeSnippet, toAntigravity };
