const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

function pipeToAgent(target, prompt, name) {
  switch (target) {
    case 'cursor':
      return pipeToCursor(prompt, name);
    case 'claude':
      return pipeToClaude(prompt);
    case 'opencode':
      return pipeToOpenCode(prompt);
    default:
      throw new Error(`Unknown pipe target: ${target}. Supported: cursor, claude, opencode`);
  }
}

function pipeToCursor(prompt, name) {
  const filePath = path.join(process.cwd(), '.cursorrules');
  fs.writeFileSync(filePath, `# .cursorrules\n# Generated by Meta-Prompt Architect\n\n${prompt}`, 'utf-8');
  console.log(`Wrote prompt to ${filePath} — Cursor will pick it up automatically.`);
}

function pipeToClaude(prompt) {
  try {
    execSync(`claude`, {
      input: prompt,
      stdio: ['pipe', 'inherit', 'inherit'],
      timeout: 300000
    });
  } catch (err) {
    if (err.status !== null) {
      console.error(`Claude exited with code ${err.status}`);
    } else {
      console.error('Failed to pipe to Claude. Is the Claude Code CLI installed? (npm i -g @anthropic-ai/claude-code)');
    }
  }
}

function pipeToOpenCode(prompt) {
  try {
    execSync(`opencode`, {
      input: prompt,
      stdio: ['pipe', 'inherit', 'inherit'],
      timeout: 300000
    });
  } catch (err) {
    if (err.status !== null) {
      console.error(`OpenCode exited with code ${err.status}`);
    } else {
      console.error('Failed to pipe to OpenCode. Is OpenCode installed? (npm i -g opencode)');
    }
  }
}

module.exports = { pipeToAgent, pipeToCursor, pipeToClaude, pipeToOpenCode };
