const fs = require('fs');
const os = require('os');
const path = require('path');
const { execSync } = require('child_process');

const HEADER = 'Generated by Meta-Prompt Architect';

function safeName(name) {
  return String(name || 'generated-prompt').replace(/[^a-zA-Z0-9._-]/g, '_');
}

function pipeToAgent(target, prompt, name, baseDir = process.cwd()) {
  switch (target) {
    case 'cursor':
      return pipeToCursor(prompt, name, baseDir);
    case 'claude':
      return pipeToClaude(prompt);
    case 'opencode':
      return pipeToOpenCode(prompt);
    case 'aider':
      return pipeToAider(prompt);
    case 'windsurf':
      return pipeToWindsurf(prompt, name, baseDir);
    case 'continue':
      return pipeToContinue(prompt, name, baseDir);
    case 'cody':
      return pipeToCody(prompt, name, baseDir);
    case 'copilot':
      return pipeToCopilot(prompt, name, baseDir);
    default:
      throw new Error(`Unknown pipe target: ${target}. Supported: cursor, claude, opencode, aider, windsurf, continue, cody, copilot`);
  }
}

function pipeToCursor(prompt, name, baseDir = process.cwd()) {
  const filePath = path.join(baseDir, '.cursorrules');
  fs.writeFileSync(filePath, `# .cursorrules\n# ${HEADER}\n\n${prompt}`, 'utf-8');
  console.log(`Wrote prompt to ${filePath} — Cursor will pick it up automatically.`);
  return filePath;
}

function pipeToWindsurf(prompt, name, baseDir = process.cwd()) {
  const filePath = path.join(baseDir, '.windsurfrules');
  fs.writeFileSync(filePath, `# .windsurfrules\n# ${HEADER}\n\n${prompt}`, 'utf-8');
  console.log(`Wrote prompt to ${filePath} — Windsurf will pick it up automatically.`);
  return filePath;
}

function pipeToContinue(prompt, name, baseDir = process.cwd()) {
  const dir = path.join(baseDir, '.continue', 'prompts');
  fs.mkdirSync(dir, { recursive: true });
  const filePath = path.join(dir, `${safeName(name)}.prompt`);
  fs.writeFileSync(filePath, `---\ndescription: ${safeName(name)} (${HEADER})\n---\n\n${prompt}\n`, 'utf-8');
  console.log(`Wrote prompt to ${filePath} — run it in Continue with /${safeName(name)}.`);
  return filePath;
}

function pipeToCody(prompt, name, baseDir = process.cwd()) {
  const dir = path.join(baseDir, '.vscode');
  fs.mkdirSync(dir, { recursive: true });
  const filePath = path.join(dir, 'cody.json');
  let config = {};
  try {
    if (fs.existsSync(filePath)) config = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  } catch { /* malformed cody.json gets replaced with a valid one */ }
  if (!config.commands || typeof config.commands !== 'object') config.commands = {};
  config.commands[safeName(name)] = { description: HEADER, prompt };
  fs.writeFileSync(filePath, `${JSON.stringify(config, null, 2)}\n`, 'utf-8');
  console.log(`Registered custom command "${safeName(name)}" in ${filePath} — find it in Cody's custom commands.`);
  return filePath;
}

function pipeToCopilot(prompt, name, baseDir = process.cwd()) {
  const dir = path.join(baseDir, '.github');
  fs.mkdirSync(dir, { recursive: true });
  const filePath = path.join(dir, 'copilot-instructions.md');
  const marker = `## ${safeName(name)} (${HEADER})`;
  let content = '';
  if (fs.existsSync(filePath)) {
    content = fs.readFileSync(filePath, 'utf8');
    if (!content.endsWith('\n')) content += '\n';
    content += `\n${marker}\n\n${prompt}\n`;
  } else {
    content = `# Copilot Instructions\n\n${marker}\n\n${prompt}\n`;
  }
  fs.writeFileSync(filePath, content, 'utf-8');
  console.log(`Appended prompt to ${filePath} — GitHub Copilot Chat picks it up automatically.`);
  return filePath;
}

function writeAiderMessageFile(prompt) {
  const filePath = path.join(os.tmpdir(), `mpa-aider-${Date.now()}.md`);
  fs.writeFileSync(filePath, prompt, 'utf-8');
  return filePath;
}

function pipeToAider(prompt) {
  const filePath = writeAiderMessageFile(prompt);
  try {
    execSync(`aider --message-file "${filePath}"`, {
      stdio: 'inherit',
      timeout: 300000
    });
  } catch (err) {
    if (err.status !== null) {
      console.error(`Aider exited with code ${err.status}`);
    } else {
      console.error('Failed to pipe to Aider. Is it installed? (pip install aider-chat)');
    }
  } finally {
    try { fs.unlinkSync(filePath); } catch { /* temp file cleanup is best-effort */ }
  }
}

function pipeToClaude(prompt) {
  try {
    execSync(`claude`, {
      input: prompt,
      stdio: ['pipe', 'inherit', 'inherit'],
      timeout: 300000
    });
  } catch (err) {
    if (err.status !== null) {
      console.error(`Claude exited with code ${err.status}`);
    } else {
      console.error('Failed to pipe to Claude. Is the Claude Code CLI installed? (npm i -g @anthropic-ai/claude-code)');
    }
  }
}

function pipeToOpenCode(prompt) {
  try {
    execSync(`opencode`, {
      input: prompt,
      stdio: ['pipe', 'inherit', 'inherit'],
      timeout: 300000
    });
  } catch (err) {
    if (err.status !== null) {
      console.error(`OpenCode exited with code ${err.status}`);
    } else {
      console.error('Failed to pipe to OpenCode. Is OpenCode installed? (npm i -g opencode)');
    }
  }
}

module.exports = { pipeToAgent, pipeToCursor, pipeToClaude, pipeToOpenCode, pipeToAider, pipeToWindsurf, pipeToContinue, pipeToCody, pipeToCopilot, writeAiderMessageFile };
